In [1]:
import numpy as np

In [2]:
phi=np.array([[1,-1.5,2.25],[1,-0.3,0.09],[1,2.5,6.25]])

In [3]:
phi

array([[ 1.  , -1.5 ,  2.25],
       [ 1.  , -0.3 ,  0.09],
       [ 1.  ,  2.5 ,  6.25]])

In [4]:
r=np.array([[0.5,0,0],[0,2,0],[0,0,2]])

In [5]:
r

array([[0.5, 0. , 0. ],
       [0. , 2. , 0. ],
       [0. , 0. , 2. ]])

In [6]:
y=np.array([[5],[-3.4],[-1]])

In [7]:
y

array([[ 5. ],
       [-3.4],
       [-1. ]])

In [22]:
ddt=np.matmul(phi.T,r)
ddt

array([[ 0.5  ,  2.   ,  2.   ],
       [-0.75 , -0.6  ,  5.   ],
       [ 1.125,  0.18 , 12.5  ]])

In [23]:
w = np.linalg.solve(np.dot(ddt, phi), np.dot(ddt, y))
print(w)

[[-4.61607143]
 [-3.46428571]
 [ 1.96428571]]


In [24]:
sum(w)

array([-6.11607143])